# Generated by Django 2.2.15 on 2020-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="body",),
        migrations.AddField(
            model_name="homepage", name="bodyTest", field=models.TextField(blank=True),
        ),
    ]
