# Generated by Django 2.2.15 on 2020-08-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200806_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='new_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customtext',
            old_name='first_update',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customtext',
            old_name='last_update',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customtext',
            old_name='title_update',
            new_name='title',
        ),
    ]
